name: Semantic Versioning Action
description: Perform semantic versioning
inputs:
  job-image-namespace:
    description: "Job image namespace"
    required: false
    default: "" #
  job-image-version-semver:
    description: "Job image version (semver)"
    required: false
    default: "v1.0.29"
  main-branch:
    description: "Main branch"
    required: false
    default: "main"
  version-tag-regex-pattern:
    description: "Version tag regex pattern"
    required: false
    default: '/^v\d+\.\d+\.\d+$/'
  version-strategy:
    description: "Version strategy"
    required: false
    default: "none"
  version-require-confirmation:
    description: "Version require confirmation"
    required: false
    default: "true"
  version:
    description: "Version variable name"
    required: false
    default: v1.3.5
outputs: {}
runs:
  using: "composite"
  env:
    JOB_IMAGE_VERSION_SEMVER: v1.0.29

    MAIN_BRANCH: "main"
    VERSION_STRATEGY: none
    VERSION_REQUIRE_CONFIRMATION: "true"
    VERSION_VARIABLE_NAME: VERSION
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Bump Version from Variable
      if: env.VERSION_STRATEGY == 'variable-value' && env.VERSION_REQUIRE_CONFIRMATION == 'true'
      run: |
        ./semantic-versioning.sh bump-version-from-variable-value
